version: "3.8"

services:
  expense-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgresql://fepa:fepa123@fepa-postgres:5432/fepa_expense
      - RABBITMQ_URL=amqp://fepa:fepa123@fepa-rabbitmq:5672
    networks:
      - fepa-network
    # volumes:
    #   - .:/app
    #   - /app/node_modules
networks:
  fepa-network:
    name: api-gateway_fepa-network
    external: true
